config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about', to: 'homes#about'
  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  validates :name, presence: true, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }, allow_blank: true

  has_many :book_images, dependent: :destroy
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about] # top, about の2つのアクションのみログインしなくてアクセス可能にする
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user) # ログインした直後は、ユーザーの詳細ページに遷移
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  Refile.secret_key = '6d3afaec3778601452c9243ffdb9fcb961d0c0a15f67ed92000e90e48da5ff87e516874864c476603d97748790b1115498be278b6629b1479adc2e2d96295411'
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:create, :edit, :update, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to @book
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to @book
    else
      flash.now[:alert] = 'Failed to update the book.'
      render :edit
    end
  end


  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = 'Book was successfully deleted.'
    else
      flash[:alert] = 'Failed to delete the book.'
    end
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      redirect_to books_path unless current_user == @user
    elsif params[:id].present?
      @book = Book.find(params[:id])
      redirect_to books_path unless current_user == @book.user
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: []
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'Your profile has been updated successfully.'
      redirect_to user_path(@user)
    else
      flash.now[:alert] = 'Failed to update your profile.'
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless current_user == @user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<main>
  <p id="notice">
  </p>
  <div class='container'>
    <div class='row'>
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
        <% if @book.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
          </ul>
        </div>
        <% end %>

      <%= form_with(model: @book, local: true) do |form| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= form.text_field :title, class: 'form-control book_title', value: @book.title, name: 'book[title]', id: 'book_title' %>
      </div>

      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= form.text_area :body, class: 'form-control book_body', name: 'book[body]', id: 'book_body' do %><%= @book.body %><% end %>
      </div>

      <div class="form-group">
        <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" />
      </div>
      <% end %>
      <%= link_to 'Show', book_path(@book) %> |
  		<a class="back" href="/books">Back</a>
    </div>
  </div>

app/views/books/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <%= render 'users/user_info' %>

      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th colspan="3">Opinion</th>
            </tr>
          </thead>

          <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
            <%= link_to user_path(book.user) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: 'default-image.jpg' %>
            <% end %>
          </td>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
          </tbody>

        </table>

      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <%= render 'users/user_info' %>
      <div class='col-md-8 offset-md-1'>
        <h2>Book detail</h2>
        <table class='table'>
          <tbody>
            <tr>
              <td>
                  <%= link_to user_path(@book.user) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, fallback: 'default-image.jpg' %>
                  <br>
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <% if user_signed_in? && current_user.id == @book.user.id %>
                <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
                <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>!
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>!!
        </h1>
        <p>In
          <i class="fas fa-book"></i>
          <strong>Bookers</strong>,
        </p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">
        <span>Bookers</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
          <li>
             <a class="nav-link text-light" href="/users/<%= current_user.id %>">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users">
              <i class="fas fa-users"></i>Users
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/books">
              <i class="fas fa-book-open"></i>Books
            </a>
          </li>
          <li>
            <a class="nav-link text-light" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="fas fa-sign-out-alt"></i>Log out
            </a>
          </li>
          <% else %>
          <li>
            <a class="nav-link text-light" href="/">
              <i class="fas fa-home"></i>Home
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/home/about">
              <i class="fas fa-link"></i>About
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_up">
              <i class="fas fa-user-plus"></i>Sign up
            </a>
          </li>
          <li>
            <a class="nav-link text-light" href="/users/sign_in">
              <i class="fas fa-sign-in-alt"></i>Log in
            </a>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_user_info.html.erb
 <div class='container px-5 px-sm-0'>
    <div class='row'>
      <div class='col-md-3'>
        <h2>User info</h2>
        <%= link_to(user_path(@user)) do %>
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, fallback: 'default-image.jpg' %>
        <% end %>
        <table class='table'>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>
        <div class='row'>
          <a class="btn btn-outline-secondary btn-block" href="<%= edit_user_path(@user) %>">
            <i class="fas fa-user-cog"></i>
          </a>
        </div>

        <% if @book.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
              <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
          </div>
        <% end %>

        <%= form_with url: books_path, method: :post, local:true do |f| %>
        <h2 class="mt-3">New book</h2>
          <div class="form-group">
            <label for="book_title">Title</label>
            <input class="form-control" type="text" name="book[title]" id="book_title" />
          </div>
          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <textarea class="form-control" name="book[body]" id="book_body"></textarea>
          </div>

          <div class="form-group">
            <input type="submit" name="commit" value="Create Book" class="btn btn-success" data-disable-with="Create Book" />
          </div>
        <% end %>
      </div>

app/views/users/edit.html.erb
<main>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>

    <p id="notice">
    <% if flash[:notice] %>
      <p class="alert alert-success"><%= flash[:notice] %></p>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
        <% if @user.errors.any? %>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
        <% end %>
      </div>
    <% end %>
    </p>
      <%= form_with model:@user, local:true do |f| %>

        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"user_name", placeholder:@user.name, class: "form-control name" %>
        </div>

        <div class="form-group">
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60 %>
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "form-control-file user_image" %>
        </div>

        <div class="form-group">
          <label for="user_introduction">Introduction</label>
            <%= f.text_area :introduction, autofocus: true, id: "user_introduction",class: "form-control introduction" %>
          </div>

        <div class="form-group">
          <%= f.submit "Update User",class: "btn btn-secondary" %>
        </div>

      <% end %>

    </div>
  </div>
</main>

app/views/users/index.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <%= render 'user_info' %>
      <div class='col-md-8 offset-md-1'>
        <h2>Users</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>image</th>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: 'default-image.jpg' %></td>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user_path(user) %></td>
          </tr>
    <% end %>
          </tbody>

        </table>

      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <p id="notice"><%= flash[:notice] %></p>
  <%= render 'user_info' %>
        <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <tr>
              <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, fallback: 'default-image.jpg' %></td>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
          <% end %>
        </table>

      </div>
    </div>
  </div>
</main>